### ISSUE TITLE
Multiple channels to join

### ISSUE THREAD

**Issue by ranyyy** [mjsalerno/UnoBot#24]
I want the bot to join multiple channels.

**Comment by ranyyy** [comment]
from the config.ini file

**Comment by mjsalerno** [comment]
with all channels sharing the same game instance or each in their own seperate games?

**Comment by ranyyy** [comment]
@mjsalerno same instance

**Comment by mjsalerno** [comment]
I started doing this change but I don't think it makes sense. Currently if you add the bot to another channel I don't think the bot will do anything at all, maybe it would tell and receive messages. It also seems like it would be annoying for people if the bot were to have an inter-channel game. Usually the admin just makes an #uno channel and tells everyone that wants to play to join it. Having just one channel  for the game is helpful since having a conversation while a game is running is a bit hard.
