### ISSUE TITLE
Wierd bug with WILD and AI

### ISSUE THREAD

**Issue by hoerup** [mjsalerno/UnoBot#33]
With latest code, i have observed a strange bug that happens sometimes when AI tries to play a WILD - but I haven't yet been able to track it down.
```

<unoBot> Top Card: GREEN SEVEN
<unoBot> unoAI it is your turn.
<unoAI> !play GREEN WILD
<unoBot> Sorry unoAI that card is not playable. Try something like !play red wild 


```

**Comment by hoerup** [comment]
i think it's fixed in this commit
https://github.com/mjsalerno/UnoBot/pull/32/commits/5a49335098134a4359cc8b2cea712407c22f985f

**Comment by mjsalerno** [comment]
So whoever calls the playWild function should not be changing the color of the wild.

I think one of your changes changed how this function gets called. It used to be that the color would just be passed in and not changed on the actual card object but I just looked and that's no longer the case.

If possible I would like to not make new card objects because then the memory of the bot will constantly increase and constantly require garbage collection

**Comment by mjsalerno** [comment]
this should be fixed
